# --------------- TLC audit app -------------------

# general
image:
  pythonimage: zwx13/audit-python
  javaimage: zwx13/audit-java 
  tag: dev
  imagePullPolicy: Always
envVars:
  natsUrl: "nats://nats:4222"

# webhook
webhook:
  name: audit-webhook
  auditSettings:
    jsStream: "AUDIT"
    rawSubject: "audit.full"
    duplicateWindow: "180"
    retentionSeconds: "86400"
  replicaCount: 1
  port: 9770
  probes:
    readiness:
      path: /readyz
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
    liveness:
      path: /livez
      initialDelaySeconds: 10
      periodSeconds: 20
      failureThreshold: 3
    timeoutSeconds: 2

# multitenancy
multitenancy:
  name: audit-mt
  mtSettings:
    rawStream: "AUDIT"
    sourceSubj: "audit.full"
    durable: "audit-mt-filter"
    mtStream: "AUDIT_MT"
    destSubj: "audit.multitenancy"
    duplicateWindow: "180"
    retentionSeconds: "2592000"
    batchSize: "50"
    fetchWindowS: "1.0"
    idleSleepS: "0.2"
    ackWaitS: "30"
    maxDeliver: "5"
  replicaCount: 1
  probes:
    readiness:
      command: ["python3", "-c", "import os, time; exit(0 if os.path.exists('/tmp/readyz') and time.time() - os.path.getmtime('/tmp/readyz') < 25 else 1)"]
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
    liveness:
      command: ["python3", "-c", "import os, time; exit(0 if os.path.exists('/tmp/livez') and time.time() - os.path.getmtime('/tmp/livez') < 25 else 1)"]
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
    timeoutSeconds: 2
  
# alerts
alerts:
  name: audit-alerts
  backoffLimit: 3
  alertsSettings:
    alertsStream: "MT_ALERTS"
    alertsSubj: "audit.mt.alerts"
    duplicateWindow: "180"
    retentionSeconds: "2592000"

# kv
kv:
  name: audit-kv
  backoffLimit: 3
  serviceAccountName: mt-state-store
  kvSettings:
    stateKV: "MT_STATE_STORE"
    storeSubj: "audit.mt.state.store"
    retentionSeconds: "2592000"

# java tlc runner
javarunner:
  name: audit-tlc-runner
  javaRunnerSettings:
    jsStream: "AUDIT_MT"
    tlaDurable: "audit-mt-tla-filter"
    tlaSubj: "audit.multitenancy"
    tlaMessageNo: "50"
    tlaKVName: "MT_STATE_STORE"
    alertsSubj: "audit.mt.alerts"
  replicas: 1
  probes:
    readiness:
      command: ["cat", "/tmp/livez"]
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
    liveness:
      command: ["sh", "-c", "[ $(expr $(date +%s) - $(stat -c %Y /tmp/livez)) -lt 30 ]"]
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
    timeoutSeconds: 2

# ---------------- Nats dependency ---------------------
nats:
  fullnameOverride: "nats"
  config:
    jetstream:
      enabled: true
      fileStore:
        pvc:
          enabled: true
          size: 1Gi