apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.alerts.name }}
  labels:
    app: {{ .Values.alerts.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.alerts.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.alerts.name }}
    spec:
      containers:
      - name: {{ .Values.alerts.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command: ["python3"]
        args: ["python_audit/alerts.py"]
        env:
          - name: NATS_URL
            value: {{ .Values.envVars.natsUrl | quote }}
          - name: ALERTS_STREAM
            value: {{ .Values.alerts.alertsSettings.alertsStream | quote }}
          - name: ALERTS_SUBJ
            value: {{ .Values.alerts.alertsSettings.alertsSubj | quote }}
          - name: ALERTS_DUPLICATE_WINDOW
            value: {{ .Values.alerts.alertsSettings.duplicateWindow | quote }}
          - name: ALERTS_RETENTION_SECONDS
            value: {{ .Values.alerts.alertsSettings.retentionSeconds | quote }}
        readinessProbe:
          exec:
            command: {{ .Values.alerts.probes.readiness.command | toJson }}
          initialDelaySeconds: {{ .Values.alerts.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.alerts.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.alerts.probes.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.alerts.probes.readiness.failureThreshold }}
        livenessProbe:
          exec:
            command: {{ .Values.alerts.probes.liveness.command | toJson }}
          initialDelaySeconds: {{ .Values.alerts.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.alerts.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.alerts.probes.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.alerts.probes.liveness.failureThreshold }}
