apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.javarunner.name }}
  labels:
    app: {{ .Values.javarunner.name }}
spec:
  replicas: {{ .Values.javarunner.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.javarunner.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.javarunner.name }}
    spec:
      containers:
      - name: {{ .Values.javarunner.name }}
        image: {{ .Values.image.javaimage }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        env:
          - name: NATS_URL
            value: {{ .Values.envVars.natsUrl | quote }}
          - name: JS_STREAM
            value: {{ .Values.javarunner.javaRunnerSettings.jsStream | quote }}
          - name: TLA_DURABLE
            value: {{ .Values.javarunner.javaRunnerSettings.tlaDurable | quote }}
          - name: TLA_SUBJECT
            value: {{ .Values.javarunner.javaRunnerSettings.tlaSubj | quote }}
          - name: TLA_MESSAGES_NO
            value: {{ .Values.javarunner.javaRunnerSettings.tlaMessageNo | quote }}
          - name: TLA_KV_NAME
            value: {{ .Values.javarunner.javaRunnerSettings.tlaKVName | quote }}
          - name: ALERTS_SUBJECT
            value: {{ .Values.javarunner.javaRunnerSettings.alertsSubj | quote }}
        readinessProbe:
          exec:
            command: {{ .Values.javarunner.probes.readiness.command | toJson }}
          initialDelaySeconds: {{ .Values.javarunner.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.javarunner.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.javarunner.probes.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.javarunner.probes.readiness.failureThreshold }}
        livenessProbe:
          exec:
            command: {{ .Values.javarunner.probes.liveness.command | toJson }}
          initialDelaySeconds: {{ .Values.javarunner.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.javarunner.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.javarunner.probes.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.javarunner.probes.liveness.failureThreshold }}

