apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kv.name }}
  labels:
    app: {{ .Values.kv.name }}
spec:
  replicas: {{ .Values.kv.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.kv.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kv.name }}
    spec:
      containers:
      - name: {{ .Values.kv.name }}
        image: {{ .Values.image.pythonimage }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command: ["python3"]
        args: ["python_audit/mt_state_store.py"]
        env:
          - name: NATS_URL
            value: {{ .Values.envVars.natsUrl | quote }}
          - name: STATE_KV
            value: {{ .Values.kv.kvSettings.stateKV | quote }}
          - name: STORE_SUBJ
            value: {{ .Values.kv.kvSettings.storeSubj | quote }}
          - name: MT_RETENTION_SECONDS
            value: {{ .Values.kv.kvSettings.retentionSeconds | quote }}
        readinessProbe:
          exec:
            command: {{ .Values.kv.probes.readiness.command | toJson }}
          initialDelaySeconds: {{ .Values.kv.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.kv.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.kv.probes.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.kv.probes.readiness.failureThreshold }}
        livenessProbe:
          exec:
            command: {{ .Values.kv.probes.liveness.command | toJson }}
          initialDelaySeconds: {{ .Values.kv.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.kv.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.kv.probes.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.kv.probes.liveness.failureThreshold }}
