apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.multitenancy.name }}
  labels:
    app: {{ .Values.multitenancy.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.multitenancy.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.multitenancy.name }}
    spec:
      containers:
      - name: {{ .Values.multitenancy.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command: ["python3"]
        args: ["python_audit/multitenancy.py"]
        env:
          - name: NATS_URL
            value: {{ .Values.envVars.natsUrl | quote }}
          - name: RAW_STREAM
            value: {{ .Values.multitenancy.mtSettings.rawStream | quote }}
          - name: SOURCE_SUBJ
            value: {{ .Values.multitenancy.mtSettings.sourceSubj | quote }}
          - name: DURABLE
            value: {{ .Values.multitenancy.mtSettings.durable | quote }}
          - name: MT_STREAM
            value: {{ .Values.multitenancy.mtSettings.mtStream | quote }}
          - name: DEST_SUBJ
            value: {{ .Values.multitenancy.mtSettings.destSubj | quote }}
          - name: MT_DUPLICATE_WINDOW
            value: {{ .Values.multitenancy.mtSettings.duplicateWindow | quote }}
          - name: MT_RETENTION_SECONDS
            value: {{ .Values.multitenancy.mtSettings.retentionSeconds | quote }}
          - name: BATCH_SIZE
            value: {{ .Values.multitenancy.mtSettings.batchSize | quote }}
          - name: FETCH_TIMEOUT_S
            value: {{ .Values.multitenancy.mtSettings.fetchWindowS | quote }}
          - name: IDLE_SLEEP_S
            value: {{ .Values.multitenancy.mtSettings.idleSleepS | quote }}
          - name: ACK_WAIT_S
            value: {{ .Values.multitenancy.mtSettings.ackWaitS | quote }}
          - name: MAX_DELIVER
            value: {{ .Values.multitenancy.mtSettings.maxDeliver | quote }}
        readinessProbe:
          exec:
            command: {{ .Values.multitenancy.probes.readiness.command | toJson }}
          initialDelaySeconds: {{ .Values.multitenancy.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.multitenancy.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.multitenancy.probes.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.multitenancy.probes.readiness.failureThreshold }}
        livenessProbe:
          exec:
            command: {{ .Values.multitenancy.probes.liveness.command | toJson }}
          initialDelaySeconds: {{ .Values.multitenancy.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.multitenancy.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.multitenancy.probes.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.multitenancy.probes.liveness.failureThreshold }}
