apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webhook.name }}
  labels:
    app: {{ .Values.webhook.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webhook.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webhook.name }}
    spec:
      containers:
      - name: {{ .Values.webhook.name }}
        image: {{ .Values.image.pythonimage }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        env:
          - name: NATS_URL
            value: {{ .Values.envVars.natsUrl | quote }}
          - name: JS_STREAM
            value: {{ .Values.webhook.auditSettings.jsStream | quote }}
          - name: RAW_SUBJECT
            value: {{ .Values.webhook.auditSettings.rawSubject | quote }}
          - name: AUDIT_DUPLICATE_WINDOW
            value: {{ .Values.webhook.auditSettings.duplicateWindow | quote }}
          - name: RETENTION_SECONDS
            value: {{ .Values.webhook.auditSettings.retentionSeconds | quote }}
        readinessProbe:
          httpGet:
            path: {{ .Values.webhook.probes.readiness.path }}
            port: {{ .Values.webhook.port }}
          initialDelaySeconds: {{ .Values.webhook.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.webhook.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.webhook.probes.timeoutSeconds }}
          failureThreshold: {{ .Values.webhook.probes.readiness.failureThreshold }}
        livenessProbe:
          httpGet:
            path: {{ .Values.webhook.probes.liveness.path }}
            port: {{ .Values.webhook.port }}
          initialDelaySeconds: {{ .Values.webhook.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.webhook.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.webhook.probes.timeoutSeconds }}
          failureThreshold: {{ .Values.webhook.probes.liveness.failureThreshold }}
        ports:
        - containerPort: {{ .Values.webhook.port }}
