apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.name }}
  labels:
    app: {{ .Values.webhook.name }}
spec:
  selector:
    app: {{ .Values.webhook.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.webhook.port }}
      targetPort: {{ .Values.webhook.port }}
